PLAYER:
  drop: true
  chance: 50
BAT:
  drop: true
  chance: 5
BLAZE:
  drop: true
  chance: 5
BEE:
  drop: true
  chance: 5
CAT:
  drop: true
  chance: 5
CAVE_SPIDER:
  drop: true
  chance: 5
CHICKEN:
  drop: true
  chance: 5
COW:
  drop: true
  chance: 5
CREEPER:
  drop: true
  chance: 5
DROWNED:
  drop: true
  chance: 5
DOLPHIN:
  drop: true
  chance: 5
ELDER_GUARDIAN:
  drop: true
  chance: 5
ENDERMAN:
  drop: true
  chance: 5
EVOKER:
  drop: true
  chance: 5
FOX:
  drop: true
  chance: 5
GHAST:
  drop: true
  chance: 5
GUARDIAN:
  drop: true
  chance: 5
HUSK:
  drop: true
  chance: 5
HORSE:
  drop: true
  chance: 5
IRON_GOLEM:
  drop: true
  chance: 5
LLAMA:
  drop: true
  chance: 5
MAGMA_CUBE:
  drop: true
  chance: 5
MUSHROOM_COW:
  drop: true
  chance: 5
OCELOT:
  drop: true
  chance: 5
PANDA:
  drop: true
  chance: 5
PARROT:
  drop: true
  chance: 5
PHANTOM:
  drop: true
  chance: 5
PIG:
  drop: true
  chance: 5
PIG_ZOMBIE:
  drop: true
  chance: 5
PILLAGER:
  drop: true
  chance: 5
POLAR_BEAR:
  drop: true
  chance: 5
RABBIT:
  drop: true
  chance: 5
RAVAGER:
  drop: true
  chance: 5
SHEEP:
  drop: true
  chance: 5
SHULKER:
  drop: true
  chance: 5
SKELETON:
  drop: true
  chance: 5
SLIME:
  drop: true
  chance: 5
SPIDER:
  drop: true
  chance: 5
SNOWMAN:
  drop: true
  chance: 5
SQUID:
  drop: true
  chance: 5
TURTLE:
  drop: true
  chance: 5
VINDICATOR:
  drop: true
  chance: 5
VEX:
  drop: true
  chance: 5
WITCH:
  drop: true
  chance: 5
WITHER:
  drop: true
  chance: 5
WOLF:
  drop: true
  chance: 5
ZOMBIE:
  drop: true
  chance: 5
ZOMBIE_VILLAGER:
  drop: true
  chance: 5
PIGLIN:
  drop: true
  chance: 5
ZOMBIEFIED_PIGLIN:
  drop: true
  chance: 5
ZOGLIN:
  drop: true
  chance: 5
STRIDER:
  drop: true
  chance: 5
COD:
  drop: true
  chance: 5