name: Headless
version: ${project.version}
main: niewidzialny84.github.headless.Headless
api-version: 1.15
authors: [Niewidzialny84]
description: Dropping heads

commands:
  headless:
    permission: headless
    usage: /headless
    permission-message: You are not allowed to use this command.